import type { PresetDefinition } from "./types";

export const TEXT_PRESETS: PresetDefinition[] = [
  {
    id: "hero-h1",
    name: "Hero H1",
    description: "Large, bold hero heading",
    subtypes: ["heading"],
    patch: {
      semanticTag: "h1",
      typography: {
        fontFamily: "Inter",
        fontWeight: 800,
        fontSize: { value: 64, unit: "px" },
        lineHeight: { value: 1.05, unit: "unitless" },
        letterSpacing: { value: -0.03, unit: "em" },
        align: "center",
        transform: "none",
        wrap: "balance",
      },
      colorEffects: {
        color: "#111111",
        opacity: 1,
      },
      overrides: {
        mobile: {
          typography: {
            fontFamily: "Inter",
            fontWeight: 800,
            fontSize: { value: 40, unit: "px" },
            lineHeight: { value: 1.05, unit: "unitless" },
            letterSpacing: { value: -0.03, unit: "em" },
            align: "center",
            transform: "none",
            wrap: "balance",
          },
        },
      },
    },
  },
  {
    id: "section-title",
    name: "Section Title",
    description: "Standard section heading",
    subtypes: ["heading", "subheading"],
    patch: {
      semanticTag: "h2",
      typography: {
        fontFamily: "Inter",
        fontWeight: 700,
        fontSize: { value: 36, unit: "px" },
        lineHeight: { value: 1.2, unit: "unitless" },
        letterSpacing: { value: -0.02, unit: "em" },
        align: "left",
        transform: "none",
        wrap: "balance",
      },
      colorEffects: {
        color: "#111111",
        opacity: 1,
      },
      overrides: {
        mobile: {
          typography: {
            fontFamily: "Inter",
            fontWeight: 700,
            fontSize: { value: 28, unit: "px" },
            lineHeight: { value: 1.2, unit: "unitless" },
            letterSpacing: { value: -0.02, unit: "em" },
            align: "left",
            transform: "none",
            wrap: "balance",
          },
        },
      },
    },
  },
  {
    id: "eyebrow",
    name: "Eyebrow",
    description: "Small uppercase label",
    subtypes: ["subheading"],
    patch: {
      semanticTag: "h3",
      typography: {
        fontFamily: "Inter",
        fontWeight: 600,
        fontSize: { value: 14, unit: "px" },
        lineHeight: { value: 1.4, unit: "unitless" },
        letterSpacing: { value: 0.05, unit: "em" },
        align: "left",
        transform: "uppercase",
        wrap: "normal",
      },
      colorEffects: {
        color: "#6b7280",
        opacity: 1,
      },
    },
  },
  {
    id: "lead-paragraph",
    name: "Lead Paragraph",
    description: "Larger intro paragraph",
    subtypes: ["paragraph"],
    patch: {
      semanticTag: "lead",
      typography: {
        fontFamily: "Inter",
        fontWeight: 400,
        fontSize: { value: 20, unit: "px" },
        lineHeight: { value: 1.7, unit: "unitless" },
        letterSpacing: { value: 0, unit: "em" },
        align: "left",
        transform: "none",
        wrap: "normal",
      },
      colorEffects: {
        color: "#374151",
        opacity: 1,
      },
      layout: {
        widthMode: "auto",
        maxWidth: { value: 720, unit: "px" },
        margin: { top: 0, right: 0, bottom: 20, left: 0, unit: "px" },
        padding: { top: 12, right: 16, bottom: 12, left: 16, unit: "px" },
        display: "block",
        whiteSpace: "normal",
        overflow: "visible",
      },
    },
  },
  {
    id: "body",
    name: "Body",
    description: "Standard body text",
    subtypes: ["paragraph"],
    patch: {
      semanticTag: "p",
      typography: {
        fontFamily: "Inter",
        fontWeight: 400,
        fontSize: { value: 16, unit: "px" },
        lineHeight: { value: 1.6, unit: "unitless" },
        letterSpacing: { value: 0, unit: "em" },
        align: "left",
        transform: "none",
        wrap: "normal",
      },
      colorEffects: {
        color: "#111111",
        opacity: 1,
      },
      layout: {
        widthMode: "auto",
        maxWidth: { value: 640, unit: "px" },
        margin: { top: 0, right: 0, bottom: 16, left: 0, unit: "px" },
        padding: { top: 12, right: 16, bottom: 12, left: 16, unit: "px" },
        display: "block",
        whiteSpace: "normal",
        overflow: "visible",
      },
    },
  },
  {
    id: "quote",
    name: "Quote",
    description: "Styled blockquote text",
    subtypes: ["paragraph"],
    patch: {
      semanticTag: "p",
      typography: {
        fontFamily: "Inter",
        fontWeight: 500,
        fontSize: { value: 20, unit: "px" },
        lineHeight: { value: 1.7, unit: "unitless" },
        letterSpacing: { value: 0, unit: "em" },
        align: "left",
        transform: "none",
        wrap: "normal",
        italic: true,
      },
      colorEffects: {
        color: "#374151",
        opacity: 1,
      },
      layout: {
        widthMode: "auto",
        maxWidth: { value: 600, unit: "px" },
        margin: { top: 24, right: 0, bottom: 24, left: 0, unit: "px" },
        padding: { top: 16, right: 24, bottom: 16, left: 24, unit: "px" },
        display: "block",
        whiteSpace: "normal",
        overflow: "visible",
      },
      wrapper: {
        useSiteStyles: false,
        border: { enabled: true, width: 4, style: "solid", color: "#e5e7eb" },
        background: { enabled: true, color: "#f9fafb" },
      },
    },
  },
];
